[server]
host = "0.0.0.0"
port = 8388
password = "bibunbibun"

[comfy]
endpoint = "http://127.0.0.1:8188"
output_directory = "C:\\Users\\azzib\\Desktop\\ComfyUI\\common\\output"
managed_output_folder = "from_home_server"
